#pragma once

namespace glfw
{
enum class printable_key
{
  Space         = 32,
  Apostrophe    = 39,
  Comma         = 44,
  Minus         = 45,
  Period        = 46,
  Slash         = 47,
  Number_0      = 48,
  Number_1      = 49,
  Number_2      = 50,
  Number_3      = 51,
  Number_4      = 52,
  Number_5      = 53,
  Number_6      = 54,
  Number_7      = 55,
  Number_8      = 56,
  Number_9      = 57,
  Semicolon     = 59,
  Equal         = 61,
  A             = 65,
  B             = 66,
  C             = 67,
  D             = 68,
  E             = 69,
  F             = 70,
  G             = 71,
  H             = 72,
  I             = 73,
  J             = 74,
  K             = 75,
  L             = 76,
  M             = 77,
  N             = 78,
  O             = 79,
  P             = 80,
  Q             = 81,
  R             = 82,
  S             = 83,
  T             = 84,
  U             = 85,
  V             = 86,
  W             = 87,
  X             = 88,
  Y             = 89,
  Z             = 90,
  Left_Bracket  = 91,
  Backslash     = 92,
  Right_Bracket = 93,
  Grave_Accent  = 96,
  World_1       = 161,
  World_2       = 162,
};
}