#include <gtest/gtest.h>
#include <vulkan/except/runtime_error.hpp>

#include <type_traits>

static_assert(std::is_base_of_v<vulkan::exception, vulkan::out_of_host_memory>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::out_of_device_memory>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::initialization_failed>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::device_lost>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::memory_map_failed>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::layer_not_present>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::extension_not_present>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::feature_not_present>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::incompatible_driver>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::too_many_objects>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::format_not_supported>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::fragmented_pool>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::unknown_error>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::invalid_external_handle>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::fragmentation>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::invalid_opaque_capture_address>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::khr::surface_lost>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::khr::native_window_in_use>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::khr::out_of_date>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::khr::incompatible_display>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::khr::image_usage_not_supported>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::khr::video_picture_layout_not_supported>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::khr::video_profile_operation_not_supported>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::khr::video_profile_format_not_supported>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::khr::video_profile_codec_not_supported>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::khr::video_std_version_not_supported>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::khr::not_permitted>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::khr::invalid_video_std_parameters>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::khr::out_of_pool_memory>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::khr::invalid_external_handle>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::khr::invalid_opaque_capture_address>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::ext::validation_failed>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::ext::invalid_drm_format_modifier_plane_layout>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::ext::full_screen_exclusive_mode_lost>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::ext::compression_exhausted>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::ext::fragmentation>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::ext::not_permitted>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::ext::invalid_device_address>);
static_assert(std::is_base_of_v<vulkan::exception, vulkan::nv::invalid_shader>);

static_assert(std::is_base_of_v<std::exception, vulkan::out_of_host_memory>);
static_assert(std::is_base_of_v<std::exception, vulkan::out_of_device_memory>);
static_assert(std::is_base_of_v<std::exception, vulkan::initialization_failed>);
static_assert(std::is_base_of_v<std::exception, vulkan::device_lost>);
static_assert(std::is_base_of_v<std::exception, vulkan::memory_map_failed>);
static_assert(std::is_base_of_v<std::exception, vulkan::layer_not_present>);
static_assert(std::is_base_of_v<std::exception, vulkan::extension_not_present>);
static_assert(std::is_base_of_v<std::exception, vulkan::feature_not_present>);
static_assert(std::is_base_of_v<std::exception, vulkan::incompatible_driver>);
static_assert(std::is_base_of_v<std::exception, vulkan::too_many_objects>);
static_assert(std::is_base_of_v<std::exception, vulkan::format_not_supported>);
static_assert(std::is_base_of_v<std::exception, vulkan::fragmented_pool>);
static_assert(std::is_base_of_v<std::exception, vulkan::unknown_error>);
static_assert(std::is_base_of_v<std::exception, vulkan::invalid_external_handle>);
static_assert(std::is_base_of_v<std::exception, vulkan::fragmentation>);
static_assert(std::is_base_of_v<std::exception, vulkan::invalid_opaque_capture_address>);
static_assert(std::is_base_of_v<std::exception, vulkan::khr::surface_lost>);
static_assert(std::is_base_of_v<std::exception, vulkan::khr::native_window_in_use>);
static_assert(std::is_base_of_v<std::exception, vulkan::khr::out_of_date>);
static_assert(std::is_base_of_v<std::exception, vulkan::khr::incompatible_display>);
static_assert(std::is_base_of_v<std::exception, vulkan::khr::image_usage_not_supported>);
static_assert(std::is_base_of_v<std::exception, vulkan::khr::video_picture_layout_not_supported>);
static_assert(std::is_base_of_v<std::exception, vulkan::khr::video_profile_operation_not_supported>);
static_assert(std::is_base_of_v<std::exception, vulkan::khr::video_profile_format_not_supported>);
static_assert(std::is_base_of_v<std::exception, vulkan::khr::video_profile_codec_not_supported>);
static_assert(std::is_base_of_v<std::exception, vulkan::khr::video_std_version_not_supported>);
static_assert(std::is_base_of_v<std::exception, vulkan::khr::not_permitted>);
static_assert(std::is_base_of_v<std::exception, vulkan::khr::invalid_video_std_parameters>);
static_assert(std::is_base_of_v<std::exception, vulkan::khr::out_of_pool_memory>);
static_assert(std::is_base_of_v<std::exception, vulkan::khr::invalid_external_handle>);
static_assert(std::is_base_of_v<std::exception, vulkan::khr::invalid_opaque_capture_address>);
static_assert(std::is_base_of_v<std::exception, vulkan::ext::validation_failed>);
static_assert(std::is_base_of_v<std::exception, vulkan::ext::invalid_drm_format_modifier_plane_layout>);
static_assert(std::is_base_of_v<std::exception, vulkan::ext::full_screen_exclusive_mode_lost>);
static_assert(std::is_base_of_v<std::exception, vulkan::ext::compression_exhausted>);
static_assert(std::is_base_of_v<std::exception, vulkan::ext::fragmentation>);
static_assert(std::is_base_of_v<std::exception, vulkan::ext::not_permitted>);
static_assert(std::is_base_of_v<std::exception, vulkan::ext::invalid_device_address>);
static_assert(std::is_base_of_v<std::exception, vulkan::nv::invalid_shader>);

static_assert(std::is_nothrow_move_constructible_v<vulkan::out_of_host_memory>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::out_of_device_memory>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::initialization_failed>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::device_lost>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::memory_map_failed>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::layer_not_present>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::extension_not_present>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::feature_not_present>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::incompatible_driver>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::too_many_objects>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::format_not_supported>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::fragmented_pool>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::unknown_error>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::invalid_external_handle>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::fragmentation>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::invalid_opaque_capture_address>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::khr::surface_lost>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::khr::native_window_in_use>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::khr::out_of_date>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::khr::incompatible_display>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::khr::image_usage_not_supported>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::khr::video_picture_layout_not_supported>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::khr::video_profile_operation_not_supported>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::khr::video_profile_format_not_supported>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::khr::video_profile_codec_not_supported>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::khr::video_std_version_not_supported>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::khr::not_permitted>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::khr::invalid_video_std_parameters>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::khr::out_of_pool_memory>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::khr::invalid_external_handle>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::khr::invalid_opaque_capture_address>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::ext::validation_failed>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::ext::invalid_drm_format_modifier_plane_layout>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::ext::full_screen_exclusive_mode_lost>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::ext::compression_exhausted>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::ext::fragmentation>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::ext::not_permitted>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::ext::invalid_device_address>);
static_assert(std::is_nothrow_move_constructible_v<vulkan::nv::invalid_shader>);

static_assert(std::is_nothrow_move_assignable_v<vulkan::out_of_host_memory>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::out_of_device_memory>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::initialization_failed>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::device_lost>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::memory_map_failed>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::layer_not_present>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::extension_not_present>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::feature_not_present>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::incompatible_driver>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::too_many_objects>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::format_not_supported>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::fragmented_pool>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::unknown_error>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::invalid_external_handle>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::fragmentation>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::invalid_opaque_capture_address>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::khr::surface_lost>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::khr::native_window_in_use>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::khr::out_of_date>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::khr::incompatible_display>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::khr::image_usage_not_supported>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::khr::video_picture_layout_not_supported>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::khr::video_profile_operation_not_supported>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::khr::video_profile_format_not_supported>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::khr::video_profile_codec_not_supported>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::khr::video_std_version_not_supported>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::khr::not_permitted>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::khr::invalid_video_std_parameters>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::khr::out_of_pool_memory>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::khr::invalid_external_handle>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::khr::invalid_opaque_capture_address>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::ext::validation_failed>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::ext::invalid_drm_format_modifier_plane_layout>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::ext::full_screen_exclusive_mode_lost>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::ext::compression_exhausted>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::ext::fragmentation>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::ext::not_permitted>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::ext::invalid_device_address>);
static_assert(std::is_nothrow_move_assignable_v<vulkan::nv::invalid_shader>);

static_assert(std::is_nothrow_copy_constructible_v<vulkan::out_of_host_memory>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::out_of_device_memory>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::initialization_failed>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::device_lost>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::memory_map_failed>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::layer_not_present>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::extension_not_present>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::feature_not_present>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::incompatible_driver>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::too_many_objects>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::format_not_supported>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::fragmented_pool>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::unknown_error>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::invalid_external_handle>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::fragmentation>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::invalid_opaque_capture_address>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::khr::surface_lost>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::khr::native_window_in_use>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::khr::out_of_date>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::khr::incompatible_display>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::khr::image_usage_not_supported>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::khr::video_picture_layout_not_supported>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::khr::video_profile_operation_not_supported>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::khr::video_profile_format_not_supported>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::khr::video_profile_codec_not_supported>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::khr::video_std_version_not_supported>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::khr::not_permitted>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::khr::invalid_video_std_parameters>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::khr::out_of_pool_memory>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::khr::invalid_external_handle>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::khr::invalid_opaque_capture_address>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::ext::validation_failed>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::ext::invalid_drm_format_modifier_plane_layout>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::ext::full_screen_exclusive_mode_lost>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::ext::compression_exhausted>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::ext::fragmentation>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::ext::not_permitted>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::ext::invalid_device_address>);
static_assert(std::is_nothrow_copy_constructible_v<vulkan::nv::invalid_shader>);

static_assert(std::is_nothrow_copy_assignable_v<vulkan::out_of_host_memory>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::out_of_device_memory>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::initialization_failed>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::device_lost>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::memory_map_failed>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::layer_not_present>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::extension_not_present>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::feature_not_present>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::incompatible_driver>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::too_many_objects>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::format_not_supported>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::fragmented_pool>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::unknown_error>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::invalid_external_handle>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::fragmentation>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::invalid_opaque_capture_address>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::khr::surface_lost>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::khr::native_window_in_use>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::khr::out_of_date>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::khr::incompatible_display>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::khr::image_usage_not_supported>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::khr::video_picture_layout_not_supported>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::khr::video_profile_operation_not_supported>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::khr::video_profile_format_not_supported>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::khr::video_profile_codec_not_supported>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::khr::video_std_version_not_supported>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::khr::not_permitted>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::khr::invalid_video_std_parameters>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::khr::out_of_pool_memory>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::khr::invalid_external_handle>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::khr::invalid_opaque_capture_address>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::ext::validation_failed>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::ext::invalid_drm_format_modifier_plane_layout>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::ext::full_screen_exclusive_mode_lost>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::ext::compression_exhausted>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::ext::fragmentation>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::ext::not_permitted>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::ext::invalid_device_address>);
static_assert(std::is_nothrow_copy_assignable_v<vulkan::nv::invalid_shader>);